routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $obj = \App\Category::all();
    Debugbar::info($obj);
    return view('welcome');
});

Route::resource('categories', 'CategoryController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'prefix' => 'articles',
], function () {
    Route::get('/', 'ArticlesController@index')
         ->name('articles.article.index');
    Route::get('/create','ArticlesController@create')
         ->name('articles.article.create');
    Route::get('/show/{article}','ArticlesController@show')
         ->name('articles.article.show');
    Route::get('/{article}/edit','ArticlesController@edit')
         ->name('articles.article.edit');
    Route::post('/', 'ArticlesController@store')
         ->name('articles.article.store');
    Route::put('article/{article}', 'ArticlesController@update')
         ->name('articles.article.update');
    Route::delete('/article/{article}','ArticlesController@destroy')
         ->name('articles.article.destroy');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable=['title'];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    public function index()
    {
        $categories = Category::all();
        return view('categories.index', compact('categories'));
    }

    public function create()
    {
        return view('categories.create');
    }

    public function store(Request $request)
    {

        try {
            $data = $request->all();
            $category = Category::create($data);

            return redirect()->route('categories.index')->withMessage('Category Inserted Successfully.');
        } catch (QueryException $e) {
            return redirect()
                ->route('categories.create')
                ->withInput()
                ->withErrors($e->getMessage());

        }

    }

    public function show(Category $category)
    {
        return view('categories.show', compact('category'));
    }

    public function edit(Category $category)
    {
        return view('categories.edit', compact('category'));
    }

    public function update(Request $request, Category $category)
    {
        try {
            $data = $request->all();
            $category->update($data);
            return redirect()->route('categories.index')->withMessage('Category Updated Successfully.');
        } catch (QueryException $e) {
            return redirect()
                ->route('categories.create')
                ->withInput()
                ->withErrors($e->getMessage());

        }
    }

    public function destroy(Category $category)
    {
        try {
            $category->delete();
            return redirect()
                ->route('categories.index')
                ->withMessage('Category Deleted Successfully!');

        } catch (QueryException $e) {
            return redirect()
                ->route('categories.index')
                ->withInput()
                ->withErrors($e->getMessage());
        }
    }


}

resources/views/categories/create.blade.php
{!! Form::open([
        'route'=>'categories.store',
        'method'=>'post'
        ]) !!}

@include('categories.form')

{!! Form::close() !!}

resources/views/categories/edit.blade.php
{{ Form::model($category,[
       'route'=>['categories.update', $category->id],
       'method'=>'put'
       ])}}

@include('categories.form')

{{ Form::close() }}

resources/views/categories/form.blade.php
{!! Form::label('title','Category Title') !!}

{!! Form::text('title',null,[
    'placeholder'=>'Enter your Category title'
    ]) !!}

{!! Form::button('Submit',[
'type'=>'submit'
]) !!}

resources/views/categories/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: fssha
 * Date: 6/11/2019
 * Time: 4:17 PM
 */
?>
<table>
   <a href="{{route('categories.create')}}">Add Category</a>
   <tr>
       <th>Sl</th>
       <th>Title</th>
       <th>Action</th>
   </tr>
@foreach($categories as $category)
    <tr>
        <td>{{$category->id}}</td>
        <td>{{$category->title}}</td>
        <td>
            <a href="{{route('categories.edit',$category->id)}}" >Edit</a>
            <a  href="{{route('categories.show',$category->id)}}">Show</a>
            <form action="{{route('categories.destroy',$category->id)}}" method="post" style="display: inline-block">
                @csrf
                @method('delete')
                <button type="submit">Delete</button>
            </form>
        </td>
    </tr>
    @endforeach
    </table>

resources/views/categories/show.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: fssha
 * Date: 6/11/2019
 * Time: 4:18 PM
 */
?>

<a href="{{ route('categories.index') }}"> Back to List Page</a>

p><strong>Title : </strong> {{ $category->title }}</p>
<p><strong>Title : </strong> {{ $category->created_at->diffForHumans() }}</p>